from typing import List
from pydantic import BaseModel, Field

class CreativeConcept(BaseModel):
    """Concept definition generated by Creative Director Agent."""
    concept_id: str = Field(description="concept_01, concept_02, or concept_03")
    title: str
    big_idea: str
    target_icp: str
    core_pain: str
    emotional_arc: str
    visual_style: str
    hook: str
    mechanism: str
    crowdwisdom_value: str
    cta: str
    why_this_concept: str
    evidence: List[str] = Field(default_factory=list)

class Scene(BaseModel):
    """Scene within a 30-60s cinematic ad."""
    scene_number: int
    duration: float = Field(ge=1.0, le=15.0, description="Duration in seconds")
    visual: str
    camera: str
    action: str
    voiceover: str
    sound_design: str
    music: str
    on_screen_text: str
    transition: str

class Script(BaseModel):
    """Production ad script adhering to the 7-beat emotional structure."""
    concept_id: str
    title: str
    concept: CreativeConcept
    scenes: List[Scene]
    total_duration: float
    compliance_approved: bool = True

class ScriptCollection(BaseModel):
    """Collection wrapper for script generation."""
    scripts: List[Script]
